/***********************************************************************
This code is generated by the AlgoPascal translator

This code is distributed under the ALGLIB license
    (see http://www.alglib.net/copyrules.php for details)
***********************************************************************/

#include "ap.h"

/*-----------------------------------------------
This routines must be defined by the programmer:

void setpixel(int x, int y, double alpha);
-----------------------------------------------*/

void drawwufilledellipse(double x1, double y1, double x2, double y2);
void sethline(int x1, int x2, int y);
void setvline(int x, int y1, int y2);

/*************************************************************************
<<<<<<< HEAD
Ð Ð¸ÑÐ¾Ð²Ð°Ð½Ð¸Ðµ Ð·Ð°Ð¿Ð¾Ð»Ð½ÐµÐ½Ð½Ð¾Ð³Ð¾ ÑÐ»Ð»Ð¸Ð¿ÑÐ° Ñ Ð¸ÑÐ¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ð½Ð¸ÐµÐ¼
Ð¼ÐµÑ‚Ð¾Ð´Ð° Ð’Ñƒ Ð´Ð»Ñ Ð°Ð½Ñ‚Ð¸Ð°Ð»Ð¸Ð°ÑÐ¸Ð½Ð³Ð°.

Ð’ Ð¿Ñ€Ð¾Ñ†ÐµÑÑÐµ Ð·Ð°Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ Ð¸ÑÐ¿Ð¾Ð»ÑŒÐ·ÑƒÑŽÑ‚ÑÑ Ñ„ÑƒÐ½ÐºÑ†Ð¸Ð¸ SetVLine
Ð¸ SetHLine, Ñ€Ð¸ÑÑƒÑŽÑ‰Ð¸Ðµ Ð¿Ñ€ÑÐ¼Ñ‹Ðµ. ÐŸÑ€Ð¾Ð³Ñ€Ð°Ð¼Ð¼Ð¸ÑÑ‚ Ð¼Ð¾Ð¶ÐµÑ‚
Ð¿ÐµÑ€ÐµÐ¾Ð¿Ñ€ÐµÐ´ÐµÐ»Ð¸Ñ‚ÑŒ Ð¸Ñ… Ñ Ñ†ÐµÐ»ÑŒÑŽ Ð¾Ð¿Ñ‚Ð¸Ð¼Ð¸Ð·Ð°Ñ†Ð¸Ð¸ Ð±Ñ‹ÑÑ‚Ñ€Ð¾Ð´ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ
Ð¿Ñ€Ð¾Ð³Ñ€Ð°Ð¼Ð¼Ñ‹.
=======
Ðèñîâàíèå çàïîëíåííîãî ýëëèïñà ñ èñïîëüçîâàíèåì
ìåòîäà Âó äëÿ àíòèàëèàñèíãà.

Â ïðîöåññå çàïîëíåíèÿ èñïîëüçóþòñÿ ôóíêöèè SetVLine
è SetHLine, ðèñóþùèå ïðÿìûå. Ïðîãðàììèñò ìîæåò
ïåðåîïðåäåëèòü èõ ñ öåëüþ îïòèìèçàöèè áûñòðîäåéñòâèÿ
ïðîãðàììû.
>>>>>>> 58e3d87... Added Wu's antialiasing algorithms for circle, ellipsis, line
*************************************************************************/
void drawwufilledellipse(double x1, double y1, double x2, double y2)
{
    double t;
    double a;
    double b;
    double cx;
    double cy;
    double x;
    double y;
    double f;
    int ix;
    int iy;
    int i1;
    int i2;
    bool exch;

    if( x2<x1 )
    {
        t = x1;
        x1 = x2;
        x2 = t;
    }
    if( y2<y1 )
    {
        t = y1;
        y1 = y2;
        y2 = t;
    }
    if( x2-x1<y2-y1 )
    {
        exch = false;
    }
    else
    {
        exch = true;
        t = x1;
        x1 = y1;
        y1 = t;
        t = x2;
        x2 = y2;
        y2 = t;
    }
    a = (x2-x1)/2;
    b = (y2-y1)/2;
    cx = (x1+x2)/2;
    cy = (y1+y2)/2;
    t = a*a/sqrt(a*a+b*b);
    i1 = ap::ifloor(cx-t);
    i2 = ap::iceil(cx+t);
    for(ix = i1; ix <= i2; ix++)
    {
        if( 1-ap::sqr((ix-cx)/a)<0 )
        {
            continue;
        }
        y = b*sqrt(1-ap::sqr((ix-cx)/a));
        iy = ap::iceil(cy+y);
        f = iy-cy-y;
        if( !exch )
        {
            setpixel(ix, iy, 1-f);
        }
        else
        {
            setpixel(iy, ix, 1-f);
        }
        iy = ap::ifloor(cy-y);
        f = cy-y-iy;
        if( !exch )
        {
            setpixel(ix, iy, 1-f);
        }
        else
        {
            setpixel(iy, ix, 1-f);
        }
    }
    t = b*b/sqrt(a*a+b*b);
    i1 = ap::iceil(cy-t);
    i2 = ap::ifloor(cy+t);
    for(iy = i1; iy <= i2; iy++)
    {
        if( 1-ap::sqr((iy-cy)/b)<0 )
        {
            continue;
        }
        x = a*sqrt(1-ap::sqr((iy-cy)/b));
        ix = ap::ifloor(cx-x);
        f = cx-x-ix;
        if( !exch )
        {
            setpixel(ix, iy, 1-f);
        }
        else
        {
            setpixel(iy, ix, 1-f);
        }
        ix = ap::iceil(cx+x);
        f = ix-cx-x;
        if( !exch )
        {
            setpixel(ix, iy, 1-f);
        }
        else
        {
            setpixel(iy, ix, 1-f);
        }
    }
    i1 = ap::iceil(cx-a);
    i2 = ap::ifloor(cx+a);
    for(ix = i1; ix <= i2; ix++)
    {
        if( 1-ap::sqr((ix-cx)/a)<0 )
        {
            continue;
        }
        y = b*sqrt(1-ap::sqr((ix-cx)/a));
        if( !exch )
        {
            setvline(ix, ap::iceil(cy-y), ap::ifloor(cy+y));
        }
        else
        {
            sethline(ap::iceil(cy-y), ap::ifloor(cy+y), ix);
        }
    }
}


/*************************************************************************
<<<<<<< HEAD
Ð¿Ñ€Ð¾Ñ†ÐµÐ´ÑƒÑ€Ð° Ñ€Ð¸ÑÐ¾Ð²Ð°Ð½Ð¸Ñ Ð³Ð¾Ñ€Ð¸Ð·Ð¾Ð½Ñ‚Ð°Ð»ÑŒÐ½Ð¾Ð¹ Ð»Ð¸Ð½Ð¸Ð¸.
Ð¼Ð¾Ð¶ÐµÑ‚ Ð±Ñ‹Ñ‚ÑŒ Ð¿ÐµÑ€ÐµÐ¾Ð¿Ñ€ÐµÐ´ÐµÐ»ÐµÐ½Ð° Ð´Ð»Ñ Ð¾Ð¿Ñ‚Ð¸Ð¼Ð¸Ð·Ð°Ñ†Ð¸Ð¸ Ð¿Ð¾ ÑÐºÐ¾Ñ€Ð¾ÑÑ‚Ð¸
=======
ïðîöåäóðà ðèñîâàíèÿ ãîðèçîíòàëüíîé ëèíèè.
ìîæåò áûòü ïåðåîïðåäåëåíà äëÿ îïòèìèçàöèè ïî ñêîðîñòè
>>>>>>> 58e3d87... Added Wu's antialiasing algorithms for circle, ellipsis, line
*************************************************************************/
void sethline(int x1, int x2, int y)
{
    int i;

    for(i = x1; i <= x2; i++)
    {
        setpixel(i, y, double(1));
    }
}


/*************************************************************************
<<<<<<< HEAD
Ð¿Ñ€Ð¾Ñ†ÐµÐ´ÑƒÑ€Ð° Ñ€Ð¸ÑÐ¾Ð²Ð°Ð½Ð¸Ñ Ð²ÐµÑ€Ñ‚Ð¸ÐºÐ°Ð»ÑŒÐ½Ð¾Ð¹ Ð»Ð¸Ð½Ð¸Ð¸.
Ð¼Ð¾Ð¶ÐµÑ‚ Ð±Ñ‹Ñ‚ÑŒ Ð¿ÐµÑ€ÐµÐ¾Ð¿Ñ€ÐµÐ´ÐµÐ»ÐµÐ½Ð° Ð´Ð»Ñ Ð¾Ð¿Ñ‚Ð¸Ð¼Ð¸Ð·Ð°Ñ†Ð¸Ð¸ Ð¿Ð¾ ÑÐºÐ¾Ñ€Ð¾ÑÑ‚Ð¸
=======
ïðîöåäóðà ðèñîâàíèÿ âåðòèêàëüíîé ëèíèè.
ìîæåò áûòü ïåðåîïðåäåëåíà äëÿ îïòèìèçàöèè ïî ñêîðîñòè
>>>>>>> 58e3d87... Added Wu's antialiasing algorithms for circle, ellipsis, line
*************************************************************************/
void setvline(int x, int y1, int y2)
{
    int i;

    for(i = y1; i <= y2; i++)
    {
        setpixel(x, i, double(1));
    }
}


